### ISSUE TITLE
"reboot [part]" not working on rpi4, firmware reboots twice

### ISSUE THREAD

**Issue by iosabi** [raspberrypi/rpi-eeprom#206] opened 2020-08-17 02:49 UTC
**Describe the bug**
In recent raspbians it is possible to pass a partition number as the extra parameter to the `LINUX_REBOOT_CMD_RESTART2` syscall by simply calling "sudo reboot 2" where "2" is just the reset reason.

The firmware is supposed to use this reset reason to boot from a different partition, however instead it always boots from partition 0. The reset flag in PM_RSTS is set, but the bootloader immediately reboots again.

**To Reproduce**
1. Install a fresh raspbian: `unzip -p 2020-05-27-raspios-buster-lite-armhf.zip 2020-05-27-raspios-buster-lite-armhf.img | sudo dd of=/dev/mmcblk0 bs=16`
2. (optional, if debugging via UART: Modify config.txt to add disable-bt overlay, I'm using this setup)
3. Add another FAT32 MBR partition at the end (mmcblk0p3) and copy the contents of another "boot" image. 
4. Boot to raspbian, and install `firmware/stable/pieeprom-2020-07-16.bin` adding the `BOOT_UART=1` option. Reboot. (Note: I also tried 2020-04-16 and 2020-06-15 with the same results).

Then run:
5. "sudo reboot 2"

**Expected behaviour**
The reset reason is set and the bootloader loads the partition 2 (mmcblk0p3) instead of the partition 0.

Instead, the bootloader gets the reset reason, it prints on the screen "part: 2" in the first line, but right after that it reboots again now with the wrong reset reason (0x00001000) which prints the same message but with "part: 0" and proceeds to boot from partition 0.

There's also a suspicious line about uSD at 1.8V instead of 3.3V.

**Screenshots**
```
pi@raspberrypi:~$ sudo reboot 2
[   72.424077] reboot: Restarting system with command '2'

PM_RSTS: 0x00001024
RPi: BOOTLOADER release VERSION:f8d1dc69 DATE: Jul 31 2020 TIME: 14:43:42 BOOTMODE: 0x00000006 part: 2 BUILD_TIMESTAMP=1596203019 0xc3d7cbc2 0x00c03111
uSD voltage 1.8V
GLOBAL_RESET: 01 0

PM_RSTS: 0x00001000
RPi: BOOTLOADER release VERSION:f8d1dc69 DATE: Jul 31 2020 TIME: 14:43:42 BOOTMODE: 0x00000006 part: 0 BUILD_TIMESTAMP=1596203019 0xc3d7cbc2 0x00c03111
uSD voltage 3.3V
Initialising SDRAM 'Micron' 16Gb x2 total-size: 32 Gbit 3200
XHCI-STOP
xHC ver: 256 HCS: 05000420 fc000031 00e70004 HCC: 002841eb
xHC ports 5 slots 32 intrs 4
Reset USB port-power 1000 ms
Boot mode: SD (01) order f2
SD HOST: 250000000 CTL0: 0x00000000 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
SD HOST: 250000000 CTL0: 0x00000f00 BUS: 100000 Hz actual: 100000 HZ div: 2500 (1250) status: 0x1fff0000 delay: 1080
```

**Bootloader version and configuration**
```
$ vcgencmd bootloader_config
[all]
BOOT_UART=1
WAKE_ON_GPIO=1
POWER_OFF_ON_HALT=0
DHCP_TIMEOUT=45000
DHCP_REQ_TIMEOUT=4000
TFTP_FILE_TIMEOUT=30000
TFTP_IP=
TFTP_PREFIX=0
BOOT_ORDER=0xf21
SD_BOOT_MAX_RETRIES=3
NET_BOOT_MAX_RETRIES=5
ENABLE_SELF_UPDATE=1
[none]
FREEZE_VERSION=0
```

```
$ vcgencmd bootloader_version
Jul 31 2020 14:43:39
version f8d1dc69144b10b4bd78b4b6d08658ac3005726d (release)
timestamp 1596203019
```

**SD card boot (please complete the following information):**
 - OS e.g. Raspbian: 2020-05-27-raspios-buster-lite-armhf.zip
 - SD card type: Samsung Evo Plus 32GB.
 - Partition information (fdisk -l) if you are able to obtain this from another computer.

```
# fdisk -l /dev/mmcblk0
Disk /dev/mmcblk0: 29.8 GiB, 32010928128 bytes, 62521344 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x2fed7fee

Device         Boot   Start     End Sectors  Size Id Type
/dev/mmcblk0p1         8192  532479  524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2       532480 3620863 3088384  1.5G 83 Linux
/dev/mmcblk0p3      3620864 3751935  131072   64M  b W95 FAT32
```

**Comment by timg236** [comment] 2020-08-17 07:58
That's the expected behaviour. The PMIC must be reset to get the card out of 1.8V mode which will clear the PM_RSTS register. Closing as duplicate of https://github.com/raspberrypi/noobs/issues/551

**Closed by timg236** 2020-08-17 07:58 UTC
Labels: support
