### ISSUE TITLE
Yellow led are blinking constantly when I boot from USB Mass Storage

### ISSUE THREAD

**Issue by ridgarou** [raspberrypi/rpi-eeprom#147] opened 2020-06-04 12:49 UTC
**Describe the bug**
Recently I adquired a RPi4 with 8Gb and I configure it to boot from an SSD disk ina HDD external Case plugged to the Pi through a USB 3.0 port

The problem is that the Yellow led are blinking constantly and I found several process (called _kworker_) consuming a minimal amoung of CPU
![image](https://user-images.githubusercontent.com/12937207/83757383-abf92000-a670-11ea-83e3-229bd47138f5.png)

I solved "the problem" inserting an microSD card in the slot. In this moment, the yellow led dont blink and the amount os CPU consumed by this process are 0.0% (but I suspect they keep running)
![image](https://user-images.githubusercontent.com/12937207/83758477-705f5580-a672-11ea-9e05-72d24bafcfba.png)

Is like the are constantly trying read a microSD card.

I have been search through Internet and the only thing similar I found are this: https://www.raspberrypi.org/forums/viewtopic.php?t=222352 but this was two years ago

There are no fix for this annoying issue??

Thank you very much in advance :)

**To Reproduce**
1. I had installed the last version of _Raspberry Pi OS (32-bit) Lite (Version: May 2020 - Release date: 2020-05-27 - Kernel version: 4.19)_
2. I updated the firmware with `sudo rpi-update` to `Raspbian GNU/Linux 10 (buster) 5.4.44-v7l+`
3. I update the bootloader with the last beta version: `Wed May 27 17:47:29 UTC 2020 (1590601649)`
4. I updated the `cmdline.txt` file adding `usb-storage.quirks=152d:0578:u` because de system dont recognice my SSD usb case as USB Mass Storage

**Bootloader version and configuration**
>  **$ sudo rpi-eeprom-update**
> BCM2711 detected
> VL805 firmware in bootloader EEPROM
> BOOTLOADER: up-to-date
> CURRENT: Wed May 27 17:47:29 UTC 2020 (1590601649)
>  LATEST: Wed May 27 17:47:29 UTC 2020 (1590601649)
>  FW DIR: /lib/firmware/raspberrypi/bootloader/beta
> VL805: up-to-date
> CURRENT: 000137ad
>  LATEST: 000137ad

> **$ vcgencmd bootloader_version**
> May 27 2020 18:47:29
> version d648db3968cd31d4948341e09cb8a925c49d2ea1 (release)
> timestamp 1590601649

> **$ vcgencmd bootloader_config**
> [all]
> BOOT_UART=0
> WAKE_ON_GPIO=1
> POWER_OFF_ON_HALT=0
> DHCP_TIMEOUT=45000
> DHCP_REQ_TIMEOUT=4000
> TFTP_FILE_TIMEOUT=30000
> ENABLE_SELF_UPDATE=1
> DISABLE_HDMI=0
> SD_BOOT_MAX_RETRIES=1
> USB_MSD_BOOT_MAX_RETRIES=1
> BOOT_ORDER=0xf41

**USB boot (please complete the following information):**
> **$ cat /boot/cmdline.txt**
> usb-storage.quirks=152d:0578:u console=serial0,115200 console=tty1 root=PARTUUID=3ec167a4-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

> **$ sudo lsusb -vvv**
> Bus 002 Device 002: ID 152d:0578 JMicron Technology Corp. / JMicron USA Technology Corp. JMS567 SATA 6Gb/s brid                                              ge
> Device Descriptor:
>   bLength                18
>   bDescriptorType         1
>   bcdUSB               3.00
>   bDeviceClass            0
>   bDeviceSubClass         0
>   bDeviceProtocol         0
>   bMaxPacketSize0         9
>   idVendor           0x152d JMicron Technology Corp. / JMicron USA Technology Corp.
>   idProduct          0x0578 JMS567 SATA 6Gb/s bridge
>   bcdDevice            5.08
>   iManufacturer           1 JMicron
>   iProduct                2 USB to ATA/ATAPI Bridge
>   iSerial                 3 0123456789ABCDEF
>   bNumConfigurations      1
>   Configuration Descriptor:
>     bLength                 9
>     bDescriptorType         2
>     wTotalLength       0x0079
>     bNumInterfaces          1
>     bConfigurationValue     1
>     iConfiguration          0
>     bmAttributes         0x80
>       (Bus Powered)
>     MaxPower              896mA
>     Interface Descriptor:
>       bLength                 9
>       bDescriptorType         4
>       bInterfaceNumber        0
>       bAlternateSetting       0
>       bNumEndpoints           2
>       bInterfaceClass         8 Mass Storage
>       bInterfaceSubClass      6 SCSI
>       bInterfaceProtocol     80 Bulk-Only
>       iInterface              0
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x81  EP 1 IN
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst              15
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x02  EP 2 OUT
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst              15
>     Interface Descriptor:
>       bLength                 9
>       bDescriptorType         4
>       bInterfaceNumber        0
>       bAlternateSetting       1
>       bNumEndpoints           4
>       bInterfaceClass         8 Mass Storage
>       bInterfaceSubClass      6 SCSI
>       bInterfaceProtocol     98
>       iInterface              0
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x01  EP 1 OUT
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst               0
>         Command pipe (0x01)
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x82  EP 2 IN
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst               0
>         MaxStreams             32
>         Status pipe (0x02)
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x83  EP 3 IN
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst              15
>         MaxStreams             32
>         Data-in pipe (0x03)
>       Endpoint Descriptor:
>         bLength                 7
>         bDescriptorType         5
>         bEndpointAddress     0x04  EP 4 OUT
>         bmAttributes            2
>           Transfer Type            Bulk
>           Synch Type               None
>           Usage Type               Data
>         wMaxPacketSize     0x0400  1x 1024 bytes
>         bInterval               0
>         bMaxBurst               7
>         MaxStreams             32
>         Data-out pipe (0x04)
> Binary Object Store Descriptor:
>   bLength                 5
>   bDescriptorType        15
>   wTotalLength       0x0016
>   bNumDeviceCaps          2
>   USB 2.0 Extension Device Capability:
>     bLength                 7
>     bDescriptorType        16
>     bDevCapabilityType      2
>     bmAttributes   0x00000f0e
>       BESL Link Power Management (LPM) Supported
>     BESL value     3840 us
>   SuperSpeed USB Device Capability:
>     bLength                10
>     bDescriptorType        16
>     bDevCapabilityType      3
>     bmAttributes         0x00
>     wSpeedsSupported   0x000e
>       Device can operate at Full Speed (12Mbps)
>       Device can operate at High Speed (480Mbps)
>       Device can operate at SuperSpeed (5Gbps)
>     bFunctionalitySupport   1
>       Lowest fully-functional device speed is Full Speed (12Mbps)
>     bU1DevExitLat          10 micro seconds
>     bU2DevExitLat          32 micro seconds
> can't get debug descriptor: Resource temporarily unavailable
> Device Status:     0x000c
>   (Bus Powered)
>   U1 Enabled
>   U2 Enabled
> 
> Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Device Descriptor:
>   bLength                18
>   bDescriptorType         1
>   bcdUSB               3.00
>   bDeviceClass            9 Hub
>   bDeviceSubClass         0
>   bDeviceProtocol         3
>   bMaxPacketSize0         9
>   idVendor           0x1d6b Linux Foundation
>   idProduct          0x0003 3.0 root hub
>   bcdDevice            5.04
>   iManufacturer           3 Linux 5.4.44-v7l+ xhci-hcd
>   iProduct                2 xHCI Host Controller
>   iSerial                 1 0000:01:00.0
>   bNumConfigurations      1
>   Configuration Descriptor:
>     bLength                 9
>     bDescriptorType         2
>     wTotalLength       0x001f
>     bNumInterfaces          1
>     bConfigurationValue     1
>     iConfiguration          0
>     bmAttributes         0xe0
>       Self Powered
>       Remote Wakeup

> **$ sudo dmesg | grep usb**
> [    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1  smsc95xx.macaddr=DC:A6:32:B1:07:3F vc_mem.mem_base=0x3eb00000 vc_mem.mem_size=0x3ff00000  usb-storage.quirks=152d:0578:u console=ttyS0,115200 console=tty1 root=PARTUUID=3ec167a4-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
> [    0.132793] usbcore: registered new interface driver usbfs
> [    0.132883] usbcore: registered new interface driver hub
> [    0.133010] usbcore: registered new device driver usb
> [    1.032100] pci 0000:01:00.0: quirk_usb_early_handoff+0x0/0x7b8 took 45134 usecs
> [    1.175566] usbcore: registered new interface driver r8152
> [    1.175646] usbcore: registered new interface driver lan78xx
> [    1.175717] usbcore: registered new interface driver smsc95xx
> [    1.179580] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
> [    1.179617] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [    1.179650] usb usb1: Product: xHCI Host Controller
> [    1.179676] usb usb1: Manufacturer: Linux 5.4.44-v7l+ xhci-hcd
> [    1.179702] usb usb1: SerialNumber: 0000:01:00.0
> [    1.181505] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.04
> [    1.181541] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
> [    1.181573] usb usb2: Product: xHCI Host Controller
> [    1.181599] usb usb2: Manufacturer: Linux 5.4.44-v7l+ xhci-hcd
> [    1.181625] usb usb2: SerialNumber: 0000:01:00.0
> [    1.184409] usbcore: registered new interface driver uas
> [    1.184581] usbcore: registered new interface driver usb-storage
> [    1.194211] usbcore: registered new interface driver usbhid
> [    1.194236] usbhid: USB HID core driver
> [    1.544893] usb 2-2: new SuperSpeed Gen 1 USB device number 2 using xhci_hcd
> [    1.576210] usb 2-2: New USB device found, idVendor=152d, idProduct=0578, bcdDevice= 5.08
> [    1.576248] usb 2-2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
> [    1.576277] usb 2-2: Product: USB to ATA/ATAPI Bridge
> [    1.576304] usb 2-2: Manufacturer: JMicron
> [    1.576329] usb 2-2: SerialNumber: 0123456789ABCDEF
> [    1.579663] usb 2-2: UAS is blacklisted for this device, using usb-storage instead
> [    1.579794] usb 2-2: UAS is blacklisted for this device, using usb-storage instead
> [    1.579829] usb-storage 2-2:1.0: USB Mass Storage device detected
> [    1.580273] usb-storage 2-2:1.0: Quirks match for vid 152d pid 0578: 1800000
> [    1.580445] scsi host0: usb-storage 2-2:1.0
> [    1.724511] usb 1-1: new high-speed USB device number 2 using xhci_hcd
> [    1.907169] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
> [    1.907206] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
> [    1.907235] usb 1-1: Product: USB2.0 Hub
> [    6.151975] usbcore: registered new interface driver brcmfmac
>

**Comment by lurch** [comment] 2020-06-04 12:57
ping @XECDesign in case this is a "Linux thing" rather than a "bootloader thing" ? :wink:

**Comment by ghollingworth** [comment] 2020-06-04 12:57
Yes, the SD driver occasionally checks the SD card to see if you've inserted an SD card, at the same time time by default the /sys/class/leds/led0/trigger is set to mmc0 so every time it checks the LED blinks...

This is by design...

**Comment by lurch** [comment] 2020-06-04 13:49
https://www.google.com/search?q=led+trigger+linux+sysfs might provide enough info for you to change the trigger so that the LED doesn't blink every time it checks the SD card? :slightly_smiling_face:

**Comment by timg236** [comment] 2020-06-04 13:52
"The problem is that the Yellow led are blinking constantly and I found several process (called kworker) consuming a minimal amoung of CPU"
Closing because Linux behaviour is not under the control of the bootloader

**Closed by timg236** 2020-06-04 13:52 UTC
Labels: invalid

**Comment by lurch** [comment] 2020-06-05 18:17
@ridgarou Perhaps https://github.com/raspberrypi/linux/issues/3286 is useful too?

**Comment by fjgsanandres** [comment] 2020-06-08 06:47
very useful! Thanks a lot! 😄
